In [41]:
# Required Header
%matplotlib inline

import matplotlib.pyplot as plt
import networkx as nx
import numpy as ny

## Question 1: 
(a) Set A is the adjacency matrix, each element Bi of A*1 is $\sum_{j=1}^{n}(A_{ij}*1)$. Apparently, this sum is equal to the degree of vertex, that is, k.

 (b) $x=(I-\frac{1}{k}A)^{-1}*\mathbf{1}=(\frac{kI-A}{k})^{-1}*\mathbf{1}\\  
     (\frac{kI-A}{k})x=\mathbf{1}$
     for each element xj of x:  
     $\sum_{j=1}^{n}(1-\frac{1}{k}A_{ij}x_{j})=1 \\
      \sum_{j=1}^{n}(\frac{1}{k}A_{ij}x_{j})=n-1\\
      x_j=n-1$ is the Katz centrality

（c) Closeness Centralities are different among nodes

In [42]:
G1=nx.random_regular_graph(5,20,seed=None)
nx.closeness_centrality(G1, u=None, distance=None, wf_improved=True)

{6: 0.5428571428571428,
 12: 0.5757575757575758,
 18: 0.5428571428571428,
 7: 0.5757575757575758,
 17: 0.5277777777777778,
 16: 0.5428571428571428,
 3: 0.5277777777777778,
 10: 0.5277777777777778,
 5: 0.5588235294117647,
 13: 0.5588235294117647,
 19: 0.5428571428571428,
 8: 0.5428571428571428,
 9: 0.5428571428571428,
 14: 0.5428571428571428,
 15: 0.5588235294117647,
 2: 0.5135135135135135,
 11: 0.5277777777777778,
 1: 0.5277777777777778,
 4: 0.5277777777777778,
 0: 0.5277777777777778}

## Question 2:
There are two types of nodes.  
The out nodes have the same closeness centralities, which are $\frac{10-1}{3+2*6}=0.6$
The inner nodes have the same closeness centralities, wich are $\frac{10-1}{3+2*4+3*2}=0.53$

## Question 3
The centrality is $\sum_{i=1}^{n-1}(\beta\alpha^{d_i}) $

## Question 4
(a)The left 4-nodes triangle is a 3-core.  
(b) The reciprocity is 0.75

In [43]:
A=ny.array([[0,1,0,1],[1,0,1,0],[1,1,0,0],[1,0,3,0]])
b=ny.dot(A,A)
b

array([[2, 0, 4, 0],
       [1, 2, 0, 1],
       [1, 1, 1, 1],
       [3, 4, 0, 1]])

In [44]:
R=1/8*(2+2+1+1)
R

0.75

(c)$Similarity=2/2/\sqrt{5}=0.45$

## Question 5
(a)The left network is a 3-core in whole. There is no 3-core in right network.   
(b) There are five strongly connnected components shown below.

![title](Illustration.png)

(c) The local clustering coefficients are shown below:

![title](Illustration2.png)  

(d) The Q is 0.28.

In [45]:
A=ny.array([[0,1,0,0,1,0,0],[1,0,1,0,1,0,0],[0,1,0,1,0,1,1],[0,0,1,0,0,0,1],[1,1,0,0,0,1,0],[0,0,1,0,1,0,1],[0,0,1,1,0,1,0]])
A

array([[0, 1, 0, 0, 1, 0, 0],
       [1, 0, 1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0, 1, 1],
       [0, 0, 1, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 1, 0, 1],
       [0, 0, 1, 1, 0, 1, 0]])

In [46]:
delta=ny.array([[1,0],[1,0],[0,1],[0,1],[1,0],[0,1],[0,1]])
delta
d=ny.array([[2],[3],[4],[2],[3],[3],[3]])
d
d.T
B=A-ny.dot(d,d.T)/2/10
B

array([[-0.2 ,  0.7 , -0.4 , -0.2 ,  0.7 , -0.3 , -0.3 ],
       [ 0.7 , -0.45,  0.4 , -0.3 ,  0.55, -0.45, -0.45],
       [-0.4 ,  0.4 , -0.8 ,  0.6 , -0.6 ,  0.4 ,  0.4 ],
       [-0.2 , -0.3 ,  0.6 , -0.2 , -0.3 , -0.3 ,  0.7 ],
       [ 0.7 ,  0.55, -0.6 , -0.3 , -0.45,  0.55, -0.45],
       [-0.3 , -0.45,  0.4 , -0.3 ,  0.55, -0.45,  0.55],
       [-0.3 , -0.45,  0.4 ,  0.7 , -0.45,  0.55, -0.45]])

In [47]:
ny.trace(delta.T.dot(B).dot(delta))/2/10

0.27999999999999997

(e) The centrality is (n-1)(n-2)